function escapeYaml(value) {
  return String(value).replace(/"/g, '\\"');
}

export function renderFrontmatter(meta) {
  const lines = ["---"];
  for (const [key, value] of Object.entries(meta)) {
    if (value === undefined || value === null) {
      continue;
    }
    if (Array.isArray(value)) {
      lines.push(`${key}:`);
      for (const item of value) {
        lines.push(`  - "${escapeYaml(item)}"`);
      }
      continue;
    }
    if (typeof value === "boolean") {
      lines.push(`${key}: ${value ? "true" : "false"}`);
      continue;
    }
    lines.push(`${key}: "${escapeYaml(value)}"`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

export function renderMarkdownPage(meta, body) {
  return renderFrontmatter(meta) + body.trim() + "\n";
}

export function sanitizeGeneratedMarkdown(body) {
  return body.replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

export function stripMarkdownLinks(body) {
  return body.replace(/\[((?:\\.|[^\]])+)\]\((?:<[^>\n]+>|[^)\n]+)\)/g, "$1");
}

export function normalizeGeneratedMarkdown(body) {
  return sanitizeGeneratedMarkdown(
    stripMarkdownLinks(body)
      .replace(/<!--[\s\S]*?-->\n*/g, "")
      .replace(/<a\b[^>]*><\/a>\n*/g, "")
      .replace(/<details><summary>([^<]+)<\/summary>\s*<p>\s*/g, "\n**$1**\n\n")
      .replace(/\s*<\/p>\s*<\/details>/g, "\n")
      .replace(/<\/?p>/g, "")
      .replace(/Generated by gomarkdoc\s*$/m, "")
      .trim()
  );
}

export function stripLeadingHeading(body) {
  return body.replace(/^# [^\n]+\n+/, "");
}

export function stripLeadingTypedocPrelude(body) {
  return body
    .replace(/^\*\*[^*]+\*\*\n+\*{3}\n+/m, "")
    .replace(/^[^\n]+ \/ [^\n]+\n+/m, "")
    .trim();
}
